# Generated by Django 6.0 on 2025-12-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="module1_total",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="module2_total",
            field=models.IntegerField(default=5),
        ),
    ]
