# Generated by Django 5.1.14 on 2025-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_testresult_module1_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.FilePathField(
                blank=True,
                match=".*\\.(png|jpg|jpeg|gif)$",
                null=True,
                path="C:\\Users\\Admin\\Desktop\\satbot\\sat_bot_project\\media\\images",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="module1_total",
            field=models.IntegerField(default=27),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="module2_total",
            field=models.IntegerField(default=27),
        ),
    ]
