# Generated by Django 5.1.14 on 2025-12-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_question_image_alter_question_id_alter_test_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="image",
            field=models.FilePathField(
                blank=True,
                match=".*\\.(png|jpg|jpeg|gif)$",
                null=True,
                path="C:\\Users\\Admin\\Desktop\\satbot\\sat_bot_project\\media\\images",
            ),
        ),
    ]
